# This is a basic workflow to help you get started with Actions

name: "CastleEscape Test Build"

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install perl prerequisites
        run: |
          perl -MCPAN -e upgrade
          cpanm --local-lib=~/perl5 App::Prove Modern::Perl Capture::Tiny Capture::Tiny::Extended Path::Tiny File::Path Template Template::Plugin::YAML Test::Differences Text::Table CPU::Z80::Assembler Test::Cmd::Common Test::HexDifferences Data::HexDump Object::Tiny::RW Regexp::Common List::Uniq Clone

      - name: Install z88dk
        run: |
          sudo snap install --edge z88dk
          sudo snap alias z88dk.zcc zcc
          sudo snap alias z88dk.z88dk-asmpp z88dk-asmpp
          sudo snap alias z88dk.z88dk-asmstyle z88dk-style

      - name: Build all
        run: |
          export Z88DK=/snap/z88dk/current/share/z88dk
          export ZCCCFG=${Z88DK}/lib/config
          export PATH=/snap/z88dk/current/bin:$PATH
          make -C assets install
          make -C src all

